<?php
require_once("server_fundamentals/SessionHandler.php");
require_once("server_fundamentals/PostDataHeadChecker.php");
getHead("Work Order Production");


if (isset($_GET['id'])) {
  if (is_numeric($_GET['id'])) {
    $getWO = mysqlSelect($UpdatedStatusQuery . "
     
      
  left join clients_main on master_wo_2_client_id = client_id
  left join master_work_order_main_identitiy on master_wo_status = mwoid_id
  
  
  
      where master_wo_ref= " . $_GET['id'] . " 
  " . $inColsWO . "
  order by master_wo_id desc
      ");


    if (!is_array($getWO)) {
      die("Error - Work Order Not Found.");
    }
    $getWO = $getWO[0];
  } else {
    die("Error - Work Order ID Invalid");
  }
} else {
  die("Error - Expected a Work Order ID, got nothing.");
}

?>

<body>
  <div id="app">
    <div class="main-wrapper">
      <div class="navbar-bg"></div>

      <?php

      getTopBar();
      getNavbar($USER_ARRAY['user_type_mod_id']);
      ?>

      <!-- Main Content -->
      <div class="main-content">
        <section class="section">
          <div class="section-header">
            <h1>Work Order #<?php echo $_GET['id'] ?> Print View

          </div>
          <!-- TOP CONTENT BLOCKS -->

          <div class="row">
            <div class="col-12 ">
              <div class="card card-warning">
                <div class="card-header">
                  <h4><input type='button' id='btn' class="btn btn-warning" value='Print' onclick='printDiv();'></h1>
                  </h4>
                </div>

                <div id="toPrint" class="card-body text-justify">
                  <?php
                  // $c = 1;
                  // foreach ($getWO as $key => $value) {
                  //   echo 'getTableTD("'.$key.' - ".$getWO["'.$key.'"]);
                  //   <br>';

                  //   if($c%4 ==0){
                  //     echo '
                  //     ?&gt;
                  //     <br>
                  //     &lt;/tr&gt;
                  //     &lt;tr&gt;
                  //     &lt;?php <br>';
                  //   }

                  //   $c++;
                  // }
                  ?>

                  <table class="mt-0 mb-1 table table-bordered">
                    <tr>
                      <th colspan="12">Work Order Print View</th>

                    </tr>
                    <tr>
                      <?php
                      getTableTD("WO#", $getWO["mwo_ref_id"]);

                      getTableTD("Date Generated", date('d-M-Y', $getWO["mwo_dnt"]));

                      getTableTD(
                        "LWO#",
                        $getWO["mwo_repeat_wo_id"]
                      );

                      getTableTD(
                        "Repeat Type",
                        ($getWO["mwo_type"] == 1 ? "New" : ($getWO["mwo_type"] == 2 ? "Repeat" : "Repeat With Change"))
                      );


                      ?>
                    </tr>
                    <tr>
                      <?php
                      getTableTD(
                        "Sales ID",
                        $getWO["mwo_gen_on_behalf_lum_id"],
                        3
                      );

                      getTableTD(
                        "Generated By",
                        $getWO["mwo_gen_lum_id"],
                        3
                      );

                      getTableTD(
                        "Repeat Changes",
                        $getWO["mwo_repeat_wo_type"]
                      );

                      getTableTD(
                        "SUB#",
                        $getWO["master_wo_id"],
                        3
                      );

                      ?>
                    </tr>
                    <tr>
                      <?php
                      getTableTD(
                        "Client",
                        $getWO["master_wo_2_client_id"],
                        4
                      );

                      getTableTD(
                        "CCR",
                        $getWO["master_wo_extra_ccr"],
                        4
                      );

                      getTableTD(
                        "NCR",
                        $getWO["master_wo_extra_ncr"],
                        4
                      );

                      ?>
                    </tr>
                    <tr>
                      <?php
                      getTableTD(
                        "Printing End Options",
                        $getWO["master_wo_extra_print_end_ops"]
                      );

                      getTableTD(
                        "Design Name",
                        $getWO["master_wo_customer_design_name"]
                      );

                      getTableTD(
                        "Item Code",
                        $getWO["master_wo_customer_item_code"]
                      );

                      getTableTD(
                        "PO#",
                        $getWO["master_wo_customer_po"]
                      );

                      ?>
                    </tr>
                    <tr>
                      <?php
                      getTableTD(
                        "PO Date",
                        date('d-M-Y', $getWO["master_wo_po_date"])
                      );

                      getTableTD(
                        "Delivery Date",
                        date('d-M-Y', $getWO["master_wo_delivery_date"])
                      );

                      getTableTD(
                        "Customer Location",
                        $getWO["master_wo_3_customer_loc"]
                      );

                      getTableTD(
                        "Contact Person Name",
                        $getWO["master_wo_contact_person_name"]
                      );

                      ?>
                    </tr>
                    <tr>
                      <?php
                      getTableTD(
                        "Contact Mob NO",
                        $getWO["master_wo_contact_person_mob_no"],
                        4
                      );

                      getTableTD(
                        "Contact Email",
                        $getWO["master_wo_contact_person_email"],
                        4
                      );

                      getTableTD(
                        "Structure",
                        $getWO["master_wo_2_structure"],
                        4
                      );

                      ?>
                    </tr>
                    <tr>
                      <?php
                      getTableTD(
                        "Printed?",
                        $getWO["master_wo_2_type_printed"]
                      );

                      getTableTD(
                        "INK GSM Pre -Costing",
                        $getWO["master_wo_ink_gsm_pre_c"]
                      );

                      getTableTD(
                        "Application",
                        $getWO["master_wo_2_application"]
                      );

                      getTableTD(
                        "Roll Filling Options",
                        $getWO["master_wo_2_roll_fill_opts"]
                      );

                      ?>
                    </tr>
                    <tr>
                      <?php
                      getTableTD(
                        "Filling Options",
                        $getWO["master_wo_2_pouchbag_fillops"]
                      );

                      getTableTD(
                        "Fill Temperature",
                        $getWO["master_wo_2_fill_temp"]
                      );

                      getTableTD(
                        "Fill Duration",
                        $getWO["master_wo_fill_duration"]
                      );

                      getTableTD(
                        "Fill temperature",
                        $getWO["master_wo_fill_temp"]
                      );

                      ?>
                    </tr>
                    <tr>
                      <?php
                      getTableTD(
                        "Line Speed Time Duration",
                        $getWO["master_wo_line_speed"]
                      );

                      getTableTD(
                        "Dwell Time",
                        $getWO["master_wo_dwell_time"]
                      );

                      getTableTD(
                        "Seal Temp",
                        $getWO["master_wo_seal_temp"]
                      );

                      getTableTD(
                        "Design ID",
                        $getWO["master_wo_design_id"]
                      );

                      ?>
                    </tr>
                    <tr>
                      <?php
                      getTableTD(
                        "REV NO",
                        $getWO["master_wo_rev_no"]
                      );

                      getTableTD(
                        "Approved Sample WO No.",
                        $getWO["master_wo_approved_sample_wo_no"]
                      );

                      getTableTD(
                        "Pack Size",
                        $getWO["master_wo_pack_size"]
                      );

                      getTableTD(
                        "Pack Weight",
                        $getWO["master_wo_pack_weight"]
                      );

                      ?>
                    </tr>
                    <tr>
                      <?php
                      getTableTD(
                        "Pack Weight Unit",
                        $getWO["master_wo_2_pack_weight_unit"]
                      );

                      getTableTD(
                        "Quantity",
                        $getWO["master_wo_quantity"]
                      );

                      getTableTD(
                        "Units",
                        $getWO["master_wo_2_units"]
                      );

                      getTableTD(
                        "Tolerance",
                        $getWO["master_wo_quantity_tolerance"]
                      );

                      ?>
                    </tr>
                    <tr>
                      <?php

                      $layersOut = array('-', '-', '-', '-', '-');
                      for ($from = 0; $from <= 4; $from++) {
                        $thisIter = $getWO['master_wo_layer_' . ($from + 1) . '_structure'];
                        if (is_numeric($thisIter)) {
                          $getLayerOut = mysqlSelect("SELECT * FROM `materials_main` where material_show = 1  and material_id = " . $thisIter);

                          if (is_array($getLayerOut)) {
                            $layersOut[$from] = $getLayerOut[0]['material_value'];
                          }
                        }
                      }

                      getTableTD(
                        "Layers",
                        "Micron/Material",
                        2
                      );
                      getTableTD(
                        "Layer1",
                        $getWO["master_wo_layer_1_micron"] . "u /" . $layersOut[0],
                        2
                      );
                      getTableTD(
                        "Layer2",
                        $getWO["master_wo_layer_2_micron"] . "u /" . $layersOut[1],
                        2
                      );
                      getTableTD(
                        "Layer3",
                        $getWO["master_wo_layer_3_micron"] . "u /" . $layersOut[2],
                        2
                      );
                      getTableTD(
                        "Layer4",
                        $getWO["master_wo_layer_4_micron"] . "u /" . $layersOut[3],
                        2
                      );
                      getTableTD(
                        "Layer5",
                        $getWO["master_wo_layer_5_micron"] . "u /" . $layersOut[4],
                        2
                      );


                      ?>
                    </tr>

                    <tr>
                      <?php

                      getTableTD(
                        "Laser Config",
                        $getWO["master_wo_2_laser_config"],
                        6
                      );

                      getTableTD(
                        "PLY",
                        $getWO["master_wo_ply"],
                        6
                      );

                      ?>
                    </tr>
                    <tr>
                      <?php
                      getTableTD(
                        "COF",
                        $getWO["master_wo_2_extrusion_cof"]
                      );

                      getTableTD(
                        "GSM",
                        $getWO["master_wo_total_gsm"]
                      );

                      getTableTD(
                        "GSM Tolerance",
                        $getWO["master_wo_total_gsm_tolerance"]
                      );



                      ?>
                    </tr>

                    <tr>
                      <?php
                      if ($getWO["master_wo_2_structure"] == 2) {
                        $getDigitalType = mysqlSelect("SELECT * FROM `work_order_digital_master` where dm_id =" . $getWO['master_wo_pouch_type']);
                        if (!is_array($getDigitalType)) {
                          $getDigitalType['dm_img_url'] = '';
                          $getDigitalType['dm_header'] = "NOT FOUND";
                        }
                        $getDigitalType = $getDigitalType[0];

                        $col1Out = "<strong>" . $getDigitalType["dm_header"] . "</strong><br><hr>";
                        $col1Out .= "<strong>A</strong> - " . $getWO["master_wo_pouch_val_a"] . "<br>";
                        $col1Out .= "<strong>B</strong> - " . $getWO["master_wo_pouch_val_b"] . "<br>";
                        $col1Out .= "<strong>C</strong> - " . $getWO["master_wo_pouch_val_c"] . "<br>";
                        $col1Out .= "<strong>D</strong> - " . $getWO["master_wo_pouch_val_d"] . "<br>";

                        $col1Out .= "<strong>E</strong> - " . $getWO["master_wo_pouch_val_e"] . "<br>";
                        $col1Out .= "<strong>F</strong> - " . $getWO["master_wo_pouch_val_f"] . "<br>";
                        $col1Out .= "<strong>G</strong> - " . $getWO["master_wo_pouch_val_g"] . "<br>";
                        $col1Out .= "<strong>H</strong> - " . $getWO["master_wo_pouch_val_h"] . "<br>";
                        $col1Out .= "<strong>Options</strong> - " . groupConcatGetVal("work_order_ui_pouch_lap_fin", "lap_fin", $getWO['master_wo_3_pouch_lap_fin'], 'mysqlSelect');

                        getTableTD(
                          "",
                          "<img src ='" . $getDigitalType['dm_img_url'] . "' width='600px' />",
                          6
                        );
                        getTableTD(
                          "",
                          $col1Out,
                          6
                        );
                      } else if ($getWO["master_wo_2_structure"] == 1) {
                        //bag
                        $getDigitalType = mysqlSelect("SELECT * FROM `work_order_digital_master` where dm_id =" . $getWO['master_wo_bag_type']);
                        if (!is_array($getDigitalType)) {
                          $getDigitalType['dm_img_url'] = '';
                          $getDigitalType['dm_header'] = "NOT FOUND";
                        }
                        $getDigitalType = $getDigitalType[0];

                        $col1Out = "<strong>" . $getDigitalType["dm_header"] . "</strong><br><hr>";
                        $col1Out .= "<strong>A</strong> - " . $getWO["master_wo_bags_val_a"] . "<br>";
                        $col1Out .= "<strong>B</strong> - " . $getWO["master_wo_bags_val_b"] . "<br>";
                        $col1Out .= "<strong>C</strong> - " . $getWO["master_wo_bags_val_c"] . "<br>";
                        $col1Out .= "<strong>D</strong> - " . $getWO["master_wo_bags_val_d"] . "<br>";

                        $col1Out .= "<strong>E</strong> - " . $getWO["master_wo_bags_val_e"] . "<br>";
                        $col1Out .= "<strong>F</strong> - " . $getWO["master_wo_bags_val_f"] . "<br>";
                        $col1Out .= "<strong>G</strong> - " . $getWO["master_wo_bags_val_g"] . "<br>";
                        $col1Out .= "<strong>H</strong> - " . $getWO["master_wo_bags_val_h"] . "<br>";

                        getTableTD(
                          "",
                          "<img src ='" . $getDigitalType['dm_img_url'] . "' width='600px' />",
                          6
                        );
                        getTableTD(
                          "",
                          $col1Out,
                          6
                        );
                      } else if ($getWO["master_wo_2_structure"] == 3) {
                      ?>
                    <tr>
                      <?php
                        getTableTD(
                          "Winding Direction",
                          $getWO["master_wo_2_wind_dir"]
                        );

                        getTableTD(
                          "Customer Roll OD(mm)",
                          $getWO["master_wo_roll_od"]
                        );

                        getTableTD(
                          "Roll Width",
                          $getWO["master_wo_roll_width"]
                        );

                        getTableTD(
                          "Roll Cut Off Length",
                          $getWO["master_wo_roll_cutoff_len"]
                        );


                      ?>
                    </tr>
                    <tr>
                      <?php

                        getTableTD(
                          "Max Weight per Roll",
                          $getWO["master_wo_max_w_p_r"]
                        );
                        getTableTD(
                          " Max L.MTR per Roll ",
                          $getWO["master_wo_max_lmtr_p_r"]
                        );

                        getTableTD(
                          "Max IMPs per Roll",
                          $getWO["master_wo_max_imps_p_r"]
                        );

                        getTableTD(
                          " Core ID ",
                          $getWO["master_wo_2_slitting_core_id"]
                        );



                      ?>
                    </tr>
                    <tr>
                      <?php
                        getTableTD(
                          "Core Material",
                          $getWO["master_wo_2_slitting_core_material"]
                        );

                        getTableTD(
                          "Core Plugs",
                          $getWO["master_wo_2_slitting_core_plugs"]
                        );

                        getTableTD(
                          " Roll Joint Color ",
                          $getWO["master_wo_2_slitting_qc_ins"]
                        );

                        getTableTD(
                          "Max No of Joints per Roll",
                          $getWO["master_wo_max_joints"]
                        );

                      ?>
                    </tr>
                  <?php
                      }

                  ?>
                  </tr>

                  <tr>
                    <?php
                    getTableTD(
                      "Foil Print Side",
                      $getWO["master_wo_2_foil_print_side"]
                    );

                    getTableTD(
                      "Printing Method",
                      $getWO["master_wo_2_printing_method"]
                    );

                    getTableTD(
                      "Shade Card Needed",
                      $getWO["master_wo_2_printing_shade_card_needed"]
                    );

                    ?>
                  </tr>
                  <tr>
                    <?php
                    getTableTD(
                      "Printing Color Ref Type",
                      $getWO["master_wo_2_printing_color_ref_type"]
                    );

                    getTableTD(
                      "Print Approval By",
                      $getWO["master_wo_2_printing_approvalby"]
                    );

                    getTableTD(
                      "Roll Packing Instructions",
                      $getWO["master_wo_2_roll_pack_ins"]
                    );

                    getTableTD(
                      "Carton Packing Instructions",
                      $getWO["master_wo_2_carton_pack_ins"]
                    );

                    ?>
                  </tr>
                  <tr>
                    <?php
                    getTableTD(
                      "Pallet Marking Ins",
                      $getWO["master_wo_2_pallet_mark_ins"]
                    );

                    getTableTD(
                      "Pouches per Bundle",
                      $getWO["master_wo_pouch_per_bund"]
                    );

                    getTableTD(
                      "Bundles per Box",
                      $getWO["master_wo_bund_per_box"]
                    );

                    getTableTD(
                      "Pallet Type",
                      $getWO["master_wo_2_pallet_type"]
                    );

                    ?>
                  </tr>
                  <tr>
                    <?php
                    getTableTD(
                      "Container Stuffing",
                      $getWO["master_wo_2_cont_stuff"]
                    );

                    getTableTD(
                      "Max Gross Pallet Weight",
                      $getWO["master_wo_max_gross_pallet_weight"]
                    );

                    getTableTD(
                      "Pallet Dimensions",
                      $getWO["master_wo_2_pallet_dim"]
                    );

                    getTableTD(
                      "Freight Type",
                      $getWO["master_wo_2_freight_type"]
                    );

                    ?>
                  </tr>
                  <tr>
                    <?php
                    getTableTD(
                      "Cart Thickness",
                      $getWO["master_wo_cart_thick"]
                    );

                    getTableTD(
                      "Documents Needed",
                      $getWO["master_wo_3_docs"]
                    );

                    getTableTD(
                      "Generated At",
                      $getWO["master_wo_gen_dnt"]
                    );

                    getTableTD(
                      "Generated By",
                      $getWO["master_wo_gen_lum_id"]
                    );

                    ?>
                  </tr>
                  <tr>
                    <?php
                    getTableTD(
                      "WO Status",
                      $getWO["master_wo_status"]
                    );

                    getTableTD(
                      "Client Code",
                      $getWO["client_code"]
                    );

                    getTableTD(
                      "Client name",
                      $getWO["client_name"]
                    );
                    ?>

                  </tr>
                  </table>

                </div>
              </div>
            </div>
          </div>
        </section>



      </div><!-- Main Content  -->

      <?php getFooter(); ?>

    </div><!-- Main Wrapper  -->
  </div><!-- App -->
  <?php getScripts(); ?>
  <script>
    function printDiv() {

      var divToPrint = document.getElementById('toPrint');
      var htmlToPrint = '' +
        '<style type="text/css">' +
        'table th, table td {' +
        'border:1px solid #000;' +
        'padding;0.5em;' +
        '}' +
        '</style>';

      var newWin = window.open('', 'Print-Window');

      newWin.document.open();

      newWin.document.write('<html><title>Work Order: <?php echo $_GET['id'] ?> Print View</title>' + htmlToPrint + '<body onload="window.print()">' + divToPrint.innerHTML + '</body></html>');

      newWin.document.close();

      setTimeout(function() {
        newWin.close();
      }, 10);

    }
  </script>
</body>

</html>